"use client";

import { useEffect, useState } from "react";
import { CrdForm } from "./CrdForm";
import { basePath } from "@/lib/shared";

interface CrdIndexEntry {
  kind: string;
  singular: string;
  scope: string;
}

// A single entry point to every per-CRD form: pick a kind, and the same
// <CrdForm> the individual CRD pages embed renders below. The kind list comes
// from crd-schemas/index.json, generated by scripts/gen-crd-docs.mjs alongside
// the per-kind schemas — no hand-maintained list to drift.
export function CrdBuilder() {
  const [kinds, setKinds] = useState<CrdIndexEntry[] | null>(null);
  const [selected, setSelected] = useState<string>("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`${basePath}/crd-schemas/index.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`${res.status} ${res.statusText}`);
        return res.json() as Promise<CrdIndexEntry[]>;
      })
      .then((data) => {
        if (cancelled) return;
        setKinds(data);
        setSelected(data[0]?.kind ?? "");
      })
      .catch((err: Error) => {
        if (!cancelled) setError(err.message);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  if (error) {
    return (
      <p className="border border-(--rule-strong) px-6 py-10 text-[13px] text-fd-muted-foreground">
        Could not load the CRD list: {error}
      </p>
    );
  }

  if (!kinds) {
    return (
      <p className="border border-(--rule-strong) px-6 py-10 text-[13px] text-fd-muted-foreground">
        Loading CRDs...
      </p>
    );
  }

  return (
    <div className="flex flex-col gap-5">
      <div className="flex flex-col gap-1">
        <label
          htmlFor="crd-kind"
          className="text-[12px] font-semibold uppercase tracking-[0.14em] text-fd-muted-foreground"
        >
          Resource kind
        </label>
        <select
          id="crd-kind"
          className="w-full max-w-xs border border-(--rule-strong) bg-(--ground-sunk) px-3 py-2 text-[15px] text-fd-foreground outline-none focus:border-(--accent) sm:max-w-sm"
          value={selected}
          onChange={(e) => setSelected(e.target.value)}
        >
          {kinds.map((entry) => (
            <option key={entry.kind} value={entry.kind}>
              {entry.kind} ({entry.scope})
            </option>
          ))}
        </select>
      </div>

      {selected ? <CrdForm key={selected} kind={selected} /> : null}
    </div>
  );
}
