[tools]
cocogitto = "latest"
node = "24"
rust = {version = "latest", components=["rust-src","rustfmt", "llvm-tools"]}
task = "latest"
gitleaks = "latest"
claude = "latest"
rtk = "latest"
etcd = "3.5.32"
"aqua:kubernetes/kubernetes/kube-apiserver" = "1.36.2"
go = "latest"
clang = "latest"
actionlint = "latest"
hadolint = "latest"
