version: "3"

tasks:
  init:
    desc: "Init folder"
    cmds:
      - mise upgrade
      - cog install-hook -a -o
  recu:
    desc: "Recuring job like regenerating Swagger spec"
    cmds:
      - cargo run -p crdgen -- --out deploy/crd/
      - node docs/scripts/gen-crd-docs.mjs

  lint:
    desc: "Linting your project to apply good practice"
    cmds:
      - cargo fmt --check
      - cargo clippy --workspace --all-targets -- -D warnings