//! One-shot import: reads an existing Authentik instance's state and
//! generates `AuthentikGroup`/`AuthentikUser`/`AuthentikBrand`/
//! `AuthentikOutpost`/`AuthentikApplication`/`AuthentikAccessPolicy` YAML
//! for `weebo-authentik-operator` to adopt. See `.prompt/plan.md`,
//! "Route C — migration à parité" and "Trois routes possibles".
//!
//! `status.authentikId` is pre-populated in every generated CR — this is
//! the *only* legitimate way a CR attaches to a pre-existing Authentik
//! object (`.prompt/plan.md`, "Collision avec un objet existant →
//! rejet": the reconciler itself never adopts by name-matching).
//!
//! **Operational caveat, not a footnote**: a plain `kubectl apply -f`
//! does not persist the `status` block Kubernetes strips it on
//! create/update. Applying these generated CRs also needs a follow-up
//! per-object `kubectl patch <kind> <name> --subresource=status --type
//! merge -p '{"status":{"authentikId":"..."}}'` (or an equivalent
//! scripted loop) — otherwise the first real reconcile sees no
//! `authentikId` and attempt-create-first collides with the very object
//! this import was meant to adopt.

mod applications;
mod brands;
mod flows;
mod groups;
mod outposts;
mod users;

use std::path::{Path, PathBuf};

use authentik_client::apis::configuration::Configuration;
use clap::Parser;

#[derive(Parser)]
#[command(about, long_about = None)]
struct Args {
    /// Base URL of the Authentik instance to import from.
    #[arg(long)]
    authentik_url: String,
    /// API token with read access to the Authentik instance.
    #[arg(long, env = "AUTHENTIK_TOKEN")]
    authentik_token: String,
    /// Name of the `AuthentikInstance` CR that generated
    /// `AuthentikApplication` CRs should reference via
    /// `spec.instanceRef` (not generated by this tool — it's
    /// user-authored, describing how to *reach* an instance).
    #[arg(long)]
    instance_ref: String,
    /// Namespace assigned to every `AuthentikApplication`/
    /// `AuthentikAccessPolicy` CR generated in this run — matches the
    /// "migration namespace par namespace" workflow from
    /// `.prompt/plan.md`. Cluster-scoped kinds (Group/User/Brand/
    /// Outpost) are regenerated every run regardless of this value.
    #[arg(long)]
    namespace: String,
    /// Optional comma-separated allow-list of application slugs to
    /// import in this run. Defaults to every application.
    #[arg(long, value_delimiter = ',')]
    applications: Option<Vec<String>>,
    /// Output directory — one YAML file per generated CR instance.
    #[arg(long, default_value = "import-output")]
    out: PathBuf,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Same "which rustls CryptoProvider" fix applied everywhere else
    // this workspace makes its first TLS connection — see
    // `testkit::envtest::EnvTestCluster::start`.
    let _ = rustls::crypto::ring::default_provider().install_default();

    let args = Args::parse();
    std::fs::create_dir_all(&args.out)?;

    let configuration = Configuration {
        base_path: args.authentik_url.clone(),
        bearer_access_token: Some(args.authentik_token.clone()),
        ..Configuration::default()
    };

    let groups_by_pk = groups::import_groups(&configuration, &args.out).await?;
    users::import_users(&configuration, &args.out, &groups_by_pk).await?;
    let flows_by_pk = flows::flow_pk_to_slug_map(&configuration).await?;
    brands::import_brands(&configuration, &args.out, &flows_by_pk).await?;
    let outposts = outposts::import_outposts(&configuration, &args.out).await?;
    applications::import_applications(
        &configuration,
        &args.out,
        &args.instance_ref,
        &args.namespace,
        args.applications.as_deref(),
        &groups_by_pk,
        &flows_by_pk,
        &outposts,
    )
    .await?;

    eprintln!(
        "\nWrote CRDs to {}.\n\
         IMPORTANT: `kubectl apply -f` does not persist status.authentikId \
         (Kubernetes strips status on create/update) — patch each object's \
         status subresource separately before the operator's first \
         reconcile, or it will attempt-create-first and collide with the \
         object this import was meant to adopt.",
        args.out.display()
    );

    Ok(())
}

/// A Kubernetes object name must be a valid RFC 1123 DNS subdomain
/// (lowercase alphanumeric and `-`, no leading/trailing `-`) — Authentik
/// names/usernames/domains have no such constraint, so every generated
/// CR's `metadata.name` goes through this, while `spec.name`/
/// `spec.username`/etc. keep the exact original value.
pub(crate) fn slugify(input: &str) -> String {
    let mut slug = String::with_capacity(input.len());
    let mut last_was_dash = false;
    for c in input.chars() {
        if c.is_ascii_alphanumeric() {
            slug.push(c.to_ascii_lowercase());
            last_was_dash = false;
        } else if !last_was_dash {
            slug.push('-');
            last_was_dash = true;
        }
    }
    let trimmed = slug.trim_matches('-');
    let truncated = &trimmed[..trimmed.len().min(253)];
    if truncated.is_empty() {
        "unnamed".to_string()
    } else {
        truncated.to_string()
    }
}

pub(crate) fn write_cr<T: serde::Serialize>(
    out_dir: &Path,
    kind: &str,
    name: &str,
    cr: &T,
) -> anyhow::Result<()> {
    let yaml = serde_norway::to_string(cr)?;
    let path = out_dir.join(format!("{kind}-{name}.yaml"));
    std::fs::write(&path, yaml)?;
    Ok(())
}
