//! One-shot import: reads an existing Authentik instance's state and
//! generates `AuthentikGroup`/`AuthentikUser`/`AuthentikFlow`/
//! `AuthentikBrand`/`AuthentikOutpost`/`AuthentikApplication`/
//! `AuthentikAccessPolicy` YAML for `weebo-authentik-operator` to adopt.
//! See `.prompt/plan.md`,
//! "Route C — migration à parité" and "Trois routes possibles".
//!
//! `status.authentikId` is pre-populated in every generated CR — this is
//! the *only* legitimate way a CR attaches to a pre-existing Authentik
//! object (`.prompt/plan.md`, "Collision avec un objet existant →
//! rejet": the reconciler itself never adopts by name-matching).
//!
//! **Operational caveat, not a footnote**: a plain `kubectl apply -f`
//! does not persist the `status` block Kubernetes strips it on
//! create/update. Applying these generated CRs also needs a follow-up
//! per-object `kubectl patch <kind> <name> --subresource=status --type
//! merge -p '{"status":{"authentikId":"..."}}'` (or an equivalent
//! scripted loop) — otherwise the first real reconcile sees no
//! `authentikId` and attempt-create-first collides with the very object
//! this import was meant to adopt.

mod applications;
mod brands;
mod common;
mod flows;
mod groups;
mod outposts;
mod users;

use std::path::PathBuf;

use anyhow::Context;
use authentik_client::apis::configuration::Configuration;
use clap::Parser;

#[derive(Parser)]
#[command(about, long_about = None)]
struct Args {
    /// Base web URL of the Authentik instance to import from, e.g.
    /// `https://login.example.com` — the same value an `AuthentikInstance`
    /// CR's `spec.url` carries. The `/api/v3` REST path is appended here, so
    /// passing it explicitly is accepted but unnecessary.
    #[arg(long)]
    authentik_url: String,
    /// API token with read access to the Authentik instance.
    #[arg(long, env = "AUTHENTIK_TOKEN")]
    authentik_token: String,
    /// Name of the `AuthentikInstance` CR that generated
    /// `AuthentikApplication` CRs should reference via
    /// `spec.instanceRef` (not generated by this tool — it's
    /// user-authored, describing how to *reach* an instance).
    #[arg(long)]
    instance_ref: String,
    /// Namespace assigned to every `AuthentikApplication`/
    /// `AuthentikAccessPolicy` CR generated in this run — matches the
    /// "migration namespace par namespace" workflow from
    /// `.prompt/plan.md`. Cluster-scoped kinds (Group/User/Brand/
    /// Outpost) are regenerated every run regardless of this value.
    #[arg(long)]
    namespace: String,
    /// Optional comma-separated allow-list of application slugs to
    /// import in this run. Defaults to every application.
    #[arg(long, value_delimiter = ',')]
    applications: Option<Vec<String>>,
    /// Output directory — one YAML file per generated CR instance.
    #[arg(long, default_value = "import-output")]
    out: PathBuf,
    /// Path to a PEM CA certificate (or concatenated bundle) to trust when
    /// connecting to the Authentik instance — use to reach an instance
    /// served by a private/self-signed CA. This is added *on top of* the
    /// platform trust store: the rustls backend goes through
    /// `rustls-platform-verifier` → `rustls-native-certs`, so the standard
    /// OpenSSL `SSL_CERT_FILE`/`SSL_CERT_DIR` env vars are honored on Linux
    /// with or without this flag (reqwest composes it via
    /// `Verifier::new_with_extra_roots`). Prefer those env vars for the
    /// system-wide case; use this flag (or `AUTHENTIK_CA_CERT`) for a root
    /// scoped to this one import run.
    #[arg(long, env = "AUTHENTIK_CA_CERT")]
    ca_cert: Option<PathBuf>,
    /// Skip TLS certificate verification entirely. Mirrors the
    /// `AuthentikInstance` CR's `spec.tls.insecureSkipVerify` — insecure,
    /// intended only for throwaway/self-signed instances.
    #[arg(long, env = "AUTHENTIK_INSECURE_SKIP_VERIFY")]
    insecure_skip_verify: bool,
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    // Same "which rustls CryptoProvider" fix applied everywhere else
    // this workspace makes its first TLS connection — see
    // `testkit::envtest::EnvTestCluster::start`.
    let _ = rustls::crypto::ring::default_provider().install_default();

    let args = Args::parse();
    std::fs::create_dir_all(&args.out)?;

    // `--authentik-url` is the web base, matching `AuthentikInstance.spec.url`;
    // the generated client needs the `/api/v3` endpoint. The importer only
    // reads, so the web half is discarded here.
    let (api_base_path, _web_base_url) = api::instance::split_urls(&args.authentik_url);

    let mut client_builder = reqwest::Client::builder();
    if let Some(ca_path) = &args.ca_cert {
        let pem = std::fs::read(ca_path)
            .with_context(|| format!("reading CA certificate {}", ca_path.display()))?;
        // `from_pem_bundle` handles both a single cert and a concatenated
        // chain; each becomes an additional trusted root. A file carrying no
        // PEM block at all parses as an *empty* bundle rather than an error,
        // which would quietly leave the run on the platform roots — same
        // check as `gateway_factory::build_http_client`.
        let certs = reqwest::Certificate::from_pem_bundle(&pem)
            .with_context(|| format!("parsing CA certificate {}", ca_path.display()))?;
        anyhow::ensure!(
            !certs.is_empty(),
            "CA certificate {} contains no PEM certificate",
            ca_path.display()
        );
        for cert in certs {
            client_builder = client_builder.add_root_certificate(cert);
        }
    }
    if args.insecure_skip_verify {
        client_builder = client_builder.danger_accept_invalid_certs(true);
    }
    let client = client_builder
        .build()
        .context("building the Authentik HTTP client")?;

    let configuration = Configuration {
        base_path: api_base_path,
        bearer_access_token: Some(args.authentik_token.clone()),
        client: reqwest_middleware::ClientBuilder::new(client).build(),
        ..Configuration::default()
    };

    let groups_by_pk = groups::import_groups(&configuration, &args.out).await?;
    users::import_users(&configuration, &args.out, &groups_by_pk).await?;
    let flows_by_pk = flows::import_flows(&configuration, &args.out).await?;
    brands::import_brands(&configuration, &args.out, &flows_by_pk).await?;
    let outposts = outposts::import_outposts(&configuration, &args.out).await?;
    let lookups = applications::ImportLookups {
        groups_by_pk: &groups_by_pk,
        flows_by_pk: &flows_by_pk,
        outposts: &outposts,
    };
    applications::import_applications(
        &configuration,
        &args.out,
        &args.instance_ref,
        &args.namespace,
        args.applications.as_deref(),
        &lookups,
    )
    .await?;

    eprintln!(
        "\nWrote CRDs to {}.\n\
         IMPORTANT: `kubectl apply -f` does not persist status.authentikId \
         (Kubernetes strips status on create/update) — patch each object's \
         status subresource separately before the operator's first \
         reconcile, or it will attempt-create-first and collide with the \
         object this import was meant to adopt.",
        args.out.display()
    );

    Ok(())
}
