[package]
name = "testkit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api = { workspace = true }
application = { workspace = true }
kube = { workspace = true }
wiremock = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
envtest = "0.3"
rustls = { workspace = true }
