[package]
name = "adapters-outbound"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain = { workspace = true }
api = { workspace = true }
application = { workspace = true }
authentik-client = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
vaultrs = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
testkit = { workspace = true }
tokio = { workspace = true }
wiremock = { workspace = true }
