{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "weebo-authentik.fullname" . }}
  labels:
    {{- include "weebo-authentik.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "weebo-authentik.selectorLabels" . | nindent 6 }}
{{- end -}}
